In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import linear_model

In [4]:
df=pd.read_csv("D:\\madiha study\\data\\homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
new_df = df.drop('price',axis='columns')
new_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [6]:
price=df.price
price

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [7]:
!pip install matplotlib

In [31]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.xlabel("area")
plt.ylabel("price")
plt.scatter(new_df, price,marker='+',color='red')

In [9]:

reg = linear_model.LinearRegression()
reg.fit(new_df,price)


LinearRegression()

In [10]:
reg.predict([[3300]])

C:\Users\Muhammad Awais\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [11]:
reg.coef_

array([135.78767123])

In [12]:
reg.intercept_   

180616.43835616432

In [13]:
# y=m*x+b       (b is intercept, x is area,m is slope->coef)
135.78767123*3300+180616.43835616432


628715.7534151643

In [14]:
# similarly we predict the 2nd value
reg.predict([[5000]])

C:\Users\Muhammad Awais\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [15]:
135.78767123*5000+180616.43835616432

859554.7945061643

In [16]:
# Generate CSV file with list of home price predictions

In [17]:
d=pd.read_csv("D:\\madiha study\\data\\area.csv")
d.head(3)

area
0  1000
1  1500
2  2300

In [18]:
p=reg.predict(d)

In [19]:
d["price"]=p
d

area         price
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   2800  5.608219e+05
4   3540  6.613048e+05
5   4120  7.400616e+05
6   4560  7.998082e+05
7   5590  9.396695e+05
8   3460  6.504418e+05
9   4750  8.256079e+05
10  2300  4.929281e+05
11  9000  1.402705e+06
12  8600  1.348390e+06
13  7100  1.144709e+06

In [20]:
d.to_csv("predictions.csv")   # in this way the sheet along with index like 1,2,3,4,5  etc

In [21]:
# we write the above statement as 
#d.to_csv("prediction.csv",index=False) # then there will b no numbering

In [22]:
%matplotlib inline
#plt.xlabel("area")
#plt.ylabel("price")
plt.scatter(df.area,df.price,marker='+',color='red')

In [23]:
# Another example of single variable

In [24]:
df=pd.read_csv("D:\\madiha study\\Book1.csv")
df.head()

year  per_capita_income_(US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [25]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.scatter(df.year,df.per_capita_income(US$),marker="+")

SyntaxError: invalid syntax (762751079.py, line 3)

In [26]:
df.year

0    1970
1    1971
2    1972
3    1973
4    1974
5    1975
6    1976
7    1977
8    1978
9    1979
Name: year, dtype: int64

In [27]:
df.per_capita_income_(US$)

SyntaxError: invalid syntax (4158268834.py, line 1)

In [28]:
new_dfs=df.drop("per_capita_income (US$)",axis="columns")
new_dfs

KeyError: "['per_capita_income (US$)'] not found in axis"

In [ ]:
per_capita_income=df.\tper_capita_income(US$)
per_capita_income

In [ ]:
reg=linear_model.linearRegression()
reg.fit(df_news,per capita income(US$))

In [30]:
pip install -U matplotlib

   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.0 MB 4.2 MB/s eta 0:00:02
   --------- ------------------------------ 1.8/8.0 MB 4.6 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.0 MB 5.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.0 MB 6.2 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.0 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 5.4 MB/s eta 0:00:00
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.9.2
    Uninstalling matplotlib-3.9.2:
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\users\\muhammad awais\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_agg.cp312-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [110]:
X=df.iloc[ :,:-1].values
y=df.iloc[:,:3].values

In [111]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [112]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)