In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [72]:
df=pd.read_csv("D:\\madiha study\\data\\homeprice.csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [73]:
 # the way we will take the median if there is no value in the dataset to solve that matter
df.bedrooms.median()

4.0

In [74]:
# to remove the fraction part if the median is 4.5 etc then we code like follow:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [75]:
# then put this median number into data like:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [76]:
reg=linear_model.LinearRegression()
reg.fit(df.drop("price",axis="columns"),df.price)

LinearRegression()

In [77]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [78]:
reg.intercept_

221323.0018654043

In [79]:
#Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old
reg.predict([[2500,4,5]])

C:\Users\Muhammad Awais\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [80]:
  df=pd.read_csv("D:\\madiha study\\data\\hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [81]:
df.experience=df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [82]:
!pip install word2number

In [83]:
from word2number import w2n

In [84]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [85]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [86]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)
df['test_score(out of 10)']


0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [87]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [92]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [93]:
reg.predict([[10,7,10]])

C:\Users\Muhammad Awais\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([81239.3309577])

In [94]:
reg.predict([[2,9,6]])

C:\Users\Muhammad Awais\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])